version: "3"
services:
  hello_world:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hello_word:latest
    container_name: hello_world
    hostname: hello_world
    ports:
      - 9090:8080
