version: "3"
services:
  hello_world:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hello_word:latest
    container_name: hello_world
    hostname: hello_world
    ports:
      - 9098:8080

  hello_world-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: hello_word:develop
    container_name: hello_world-dev
    hostname: hello_world-dev
    volumes:
      - ./hello_world:/usr/src/app
    ports:
      - 9090:8080
